version: '3.9'

services:
  app:
    build: ./
    working_dir: /videos
    # Persist bash history config
    volumes:
      - ../:/videos
      # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
